version: '3'

services:
  php:
    container_name: php
    build:
      context: ./php
    volumes:
      - ../:/var/www/app
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    ports:
      - "9004:9001"
    environment:
      - 'DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_ROOT_PASSWORD}@mysql:3306/${MYSQL_DATABASE}'
      - 'MAILER_DSN=smtp://mailer:1025'
    restart: 'on-failure:5'

  nginx:
    container_name: nginx
    image: nginx:stable
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ../:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=${APP_HOSTNAME}
    restart: 'on-failure:5'

  mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0.23
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    command: --lower_case_table_names=1
    restart: 'on-failure:5'

  mailer:
    container_name: mailer
    image: schickling/mailcatcher
    ports: ["1025", "1080"]

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    volumes:
      - ../:/var/www/app
    networks:
      - app-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

